Fix spec.json and release.json
nio-blocks/scikit pull request #4
Opened 2017-07-26 22:48 UTC by hansmosh

2017-07-27 20:17 UTC, dorzel requested changes
Neither the release.json or the spec.json has the batch tweet classifier block

2017-07-28 00:39 UTC, hansmosh commented
@dorzel I didn't add that block because I wasn't sure that block should even be in there. Should it really be BatchTextClassifier? I might change the block name in that class.

2017-07-28 15:41 UTC, dorzel commented
@hansmosh yeah it does look like it should be called that instead

2017-07-28 17:34 UTC, cowleyk approved these changes

2017-07-28 17:34 UTC, merged